# Generated by Django 2.0.1 on 2018-01-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentweather', '0002_auto_20180126_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Station',
            new_name='StationWeather',
        ),
    ]
