# Generated by Django 2.0.1 on 2018-02-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentweather', '0003_auto_20180126_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
